From ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_VERSION="3.6.5"

#Install Packages
RUN apt-get update -y
RUN apt-get install -y openjdk-8-jdk build-essential autoconf libtool g++ gettext make mono-complete checkinstall software-properties-common llvm cmake wget git nano nasm yasm zip unzip pkg-config libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev mysql-client default-libmysqlclient-dev


ADD /root/dockerfiles/Debug /root/Debug
WORKDIR /root/Debug
EXPOSE 8090

RUN /root/Debug/EngineService.exe
